
# html lang
language: es

# main menu navigation
menu:
  Comunidad: /comunidad/
  Paquetes: /paquetes/
  Experiencias: /experiencias/

#url, title, class, onclick
menu_button:
  user:
    url: /cotizaciones/
    title: "Cotizaciones"
    class: "pure-button-primary"

# Miscelaneous
logo:
  enabled: true
  width: 180
  height: 80
  url: images/mamba-logo.svg
front_page:
  enabled: true
  url_lg: images/front-page-lg.jpg
  url_md: images/front-page-md.jpg

# stylesheets loaded in the <head>
# source/css/
stylesheets:
  custom:
    - custom.css
    - responsive-menu.css
    - colors.css
    - pure.css
    - media.css
    - pure-responsive-grids.css

# scripts loaded in the end of the body
#name > (url, async:async) type
scripts:
  google_analytics:
    url: https://www.google-analytics.com/analytics.js
    async: async
    callback: google_async("UA-101494881-1")
  sharethis:
    url: //platform-api.sharethis.com/js/sharethis.js#property=5ab97990ce89f000136419fd&product=inline-share-buttons
    async: async
  disqus:
    url: /disqus.js?ver=9
    async: async
    callback: disqus_async("jaimelias")
	
local_scripts:
  loadJS:
    - loadJS.js
  site:
    - site.js
  events:
    - events.js

##remove loadCSS to hit 100% on google

#true, false or API key for facebook	
social:
  twitter: true
  facebook: true
  gplus: true
  pinterest: true
  email: true
  disqus_user: jaimelias
  
#blog config
hero:
    home:
      enable: true
      title: "Creadores de Experiencias"
    blog:
      enable: true
      title: "#ComunidadMamba"
      description: "Forma parte de la comunidad creativa de emprendedores más influyente y radical de Panamá"
      button:
        text: "Únete Gratis"
        url:
        onclick: show_modal()
    newsletter:
      enable: true
      title: "Expón tu talento a las marcas"
      description: "Únete a la #ComunidadMamba y lleva tu talento al siguiente al siguiente nivel. Fotografía, cine, modelaje, gastronomía..."
      button:
        text: "Suscríbete Gratis"
        url:
        onclick: show_modal()