
# html lang
language: es

# main menu navigation
menu:
  Comunidad: /comunidad/
  Experiencias: /experiencias/
  Paquetes:
    url: /#experiences
    id: packages-link

#url, title, class, onclick
menu_button:
  user:
    onclick: show_modal("estimates");
    title: "Cotizaciones"
    url: "#"
    class: "pure-button-primary"
	
footer_menu:
  Nosotros: /nosotros/
  Empleos: /empleos/
  Acuerdo General: /acuerdo-general/
  
algolia:
  title: Encuentra experiencias inolvidables...
  
estimates:
  title: Cotiza con los expertos
  button: Enviar solicitud
  base64_url:

# Miscelaneous
logo:
  enabled: true
  width: 180
  height: 80
  url: images/mamba-logo.svg
front_page:
  enabled: true
  url_lg: images/front-page-lg.jpg
  url_md: images/front-page-md.jpg

# stylesheets loaded in the <head>
# source/css/
stylesheets:
  custom:
    - custom.css
    - responsive-menu.css
    - colors.css
    - pure.css
    - media.css
    - pure-responsive-grids.css
  datepicker:
    - datepicker.css
  instantsearchCSS:
    - instantsearch.custom.css

# scripts loaded in the end of the body
#name > (url, async:async) type
scripts:
  hogan:
    url: /hogan.js
    position: top
  date_picker:
    url: /datepicker.min.js?ver=2
    async: async
    callback: date_picker()
    position: bottom
  google_analytics:
    url: https://www.google-analytics.com/analytics.js
    async: async
    callback: google_async("UA-101494881-1")
    position: bottom
  sharethis:
    url: //platform-api.sharethis.com/js/sharethis.js#property=5ab97990ce89f000136419fd&product=inline-share-buttons
    async: async
    position: bottom
  disqus:
    url: /disqus.js?ver=9
    async: async
    callback: disqus_async("jaimelias")
    position: bottom
  instantsearchJS:
    url: https://cdn.jsdelivr.net/npm/instantsearch.js@2.2.5/dist/instantsearch.min.js
    async: async
    callback: async_instantsearch()
    position: bottom
	
local_scripts:
  loadJS:
    - loadJS.js
  site:
    - site.js
  events:
    - events.js
  instantsearchCONF:
    - instantsearch.js

##remove loadCSS to hit 100% on google

#true, false or API key for facebook	
social:
  twitter: true
  facebook: true
  gplus: true
  pinterest: true
  email: true
  disqus_user: jaimelias
  
webhook:
  base64_url: aHR0cHM6Ly9mbG93eG8uY29tL2hvb2tzL2EvOGp2OHlqbWc=
  
#blog config
hero:
    home:
      enable: true
      title: "Creadores de Experiencias"
    blog:
      enable: true
      title: "#ComunidadMamba"
      description: "Forma parte de la comunidad creativa de emprendedores más influyente y radical de Panamá"
      button:
        text: "Únete Gratis"
        url:
        onclick: show_modal("subscribe")
    newsletter:
      enable: true
      title: "Expón tu talento a las marcas"
      description: "Únete a la #ComunidadMamba y lleva tu talento al siguiente al siguiente nivel. Fotografía, cine, modelaje, gastronomía..."
      button:
        text: "Suscríbete Gratis"
        url:
        onclick: show_modal("subscribe")